version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT}:8080"
    env_file:
      - ../.env
    volumes:
      - ../src:/usr/src/app/src
      - /usr/src/app/node_modules
