version: '3'
services:
  app:
    container_name: mahjong-backend
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
    ports:
      - "8080:8080"
